language: clojure
lein: 2.7.1
before_install:
  - git clone https://github.com/billosys/clj-xbee
  - cd clj-xbee
  - lein install
  - cd ../
  - rm -rf clj-xbee
script:
  - lein build
jdk:
  - oraclejdk8
  - oraclejdk7
env:
  - LEIN_SNAPSHOTS_IN_RELEASE=true
notifications:
  email:
    - bjorn@billo.systems
